## NumPy.Random Package 

### Overall Purpose:

The purpose of the package is to build upon the existing random module in the python standard library. The existing random module has functionality for creating single random numbers and a some simple distributions. The numpy random package offers all of this functionality with the addition of generating random numbers inside numpy arrays.It also supports a larger amount of distributions with further options within those distributions.NumPy.random is also significantly faster than the standard random module for generating very large samples.   

### Simple Random Data

In [6]:
import numpy as np
from numpy import random

The .rand function allows you to create an array of a specified shape. That can be 1D by passing one number as an argument, 2D by passing two and 3D by passing three. The array will contain data from a uniform distribution over the range 0-1. For example, in the next line of code it shows a 5 row x 3 column array with all positive values. 

In [31]:
measurements = np.random.rand(3,3,3)

In [32]:
print(measurements)

[[[0.98949487 0.72005563 0.68036797]
  [0.5210059  0.81532369 0.35709735]
  [0.14588765 0.28026237 0.05740311]]

 [[0.37174214 0.92848093 0.61758531]
  [0.79586534 0.52585505 0.54838118]
  [0.03017434 0.04129941 0.55218872]]

 [[0.46946161 0.09634675 0.15877388]
  [0.19783292 0.17314592 0.38003137]
  [0.325065   0.87530286 0.07735365]]]


When no argument is passed, i.e. nothing in the parenthesis (), then a single floating point number is returned.   

In [12]:
np.random.rand()

0.5137914233835779

The .randn function will return an array (1D-3D) of samples or just one sample (depending on whether an argument is passed or not) from a normal distribution of mean = 0 and variance =1. Similiar to the .rand function only data is taken from a normal and not uniform distribution. 

In [21]:
temp_read = np.random.randn(2,3)

In [22]:
temp_read

array([[ 1.15014346,  0.7582094 , -0.72477336],
       [ 0.66023952, -0.86030215, -1.49231207]])

Randomly generated data can be manipulated using simple maths. 

In [37]:
# multiply the values in the array by 2
temp_read = np.random.randn(2,3)*2

In [38]:
temp_read

array([[4.79585601, 1.16532713, 1.29168432],
       [3.06521918, 0.87197434, 0.39534262]])

In [35]:
# multiplication and addition
temp_read = np.random.randn(2,3)*3 + 2

In [36]:
temp_read

array([[ 1.89116666,  6.19377435,  0.1314365 ],
       [ 5.22386893, -0.15294867,  2.39021797]])

The .randint function returns random integers from a discrete uniform distribution from a range of low to high, including the low but excluding the high. The size of the array that is returned can be set i.e. give me five random numbers from the list of 1-8 (including one but excluding eight)

In [127]:
# random number between 0 and 3 (inclusive of 0, exclusive of 3. The high is not set) 
np.random.randint(3)

2

In [126]:
# inclusive of 1 but excluding 5
np.random.randint(1,5)

4

In [136]:
#return 10 numbers in the array, from 3-14)
np.random.randint(3,15, size=10)

array([ 9,  4, 14, 13, 14,  6,  5, 11,  3,  7])